export const environment = {
	production: false,
	network: 'live',
	wsUrl: 'wss://nanows.numsu.dev',
	rpcUrl: 'https://nanoproxy.numsu.dev/proxy',
	principalsUrl: 'https://mynano.ninja/api/accounts/principals',
	explorerUrl: 'https://nanolooker.com',
	repInfoUrl: 'https://mynano.ninja',
	hostAccount: 'nano_3zapp5z141qpjipsb1jnjdmk49jwqy58i6u6wnyrh6x7woajeyme85shxewt',
	// network: 'beta',
	// wsUrl: 'wss://ws-beta.nanoticker.info',
	// rpcUrl: 'https://beta-proxy.nanos.cc',
	// principalsUrl: 'https://json.nanoticker.info/?file=monitors-beta',
	// explorerUrl: 'https://beta.nanocrawler.cc',
	// repInfoUrl: 'https://beta.nanocrawler.cc',
	// hostAccount: 'nano_3zapp5z141qpjipsb1jnjdmk49jwqy58i6u6wnyrh6x7woajeyme85shxewt',
};
